modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="infecticraft"
version="1.0.0"
displayName="Infecticraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Julian Hempstead, MCreator"

[[dependencies.infecticraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




